version: 0.0 #CodeDeploy 버전
os: linux
files:
  - source:  / #CodeDeploy에서 전달해 준 파일 중 desination으로 이동시킬 대상 지정 / (루트는 전체파일)
    destination: /home/ec2-user/app/step3/zip/ #source에서 지정된 파일을 받을 위치, 이후 jar를 실행하는 등은 destination에서 옮긴 파일들로 진행
    overwrite: yes #기존 파일있으면 overwrite 여부 -> yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh #엔진엑스와 연결되어 있지 않은 스프링 부트 종료
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: start.sh #엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링 부트 시작
      timeout: 60
      runas: ec2-user

  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user