version: 0.0 #CodeDeploy 버전
os: linux
files:
  - source:  / #CodeDeploy에서 전달해 준 파일 중 desination으로 이동시킬 대상 지정 / (루트는 전체파일)
    destination: /home/ec2-user/app/step2/zip/ #source에서 지정된 파일을 받을 위치, 이후 jar를 실행하는 등은 destination에서 옮긴 파일들로 진행
    overwrite: yes #기존 파일있으면 overwrite 여부 -> yes